docs: add multiple documentation

diff --git a/features.in/docs/scripts.d/50-docs-indexhtml b/features.in/docs/scripts.d/50-docs-indexhtml
--- a/features.in/docs/scripts.d/50-docs-indexhtml
+++ b/features.in/docs/scripts.d/50-docs-indexhtml
@@ -42,9 +42,12 @@ mkredir() {
 mkredir "" "$dest"	# /index.html -> docs/index.html
 
 docdir="/usr/share/doc/documentation"
-if [ -d "$docdir" ] && [ ! -d "$dest"/documentation ]; then
+for docdir in ${GLOBAL_DOCS:-}; do
+	docdir=/usr/share/doc/"$docdir"
 	### no need to replace symlinks with hardlinks by now? (-aH)
-	cp -aH "$docdir" "$dest"
-else
-	nonfatal "$docdir not found"
-fi
+	if [ -d "$docdir" ]; then
+		cp -aH "$docdir" "$dest"
+	else
+		echo "** $docdir not found" >&2
+	fi
+done
